<template>
  <div class="about">
    <h1>A site to Practice Vue.js</h1>
    <p>All fake data has been randomly generated by https://www.mockaroo.com/</p>
    <p>The images have been provided by https://i.pravatar.cc/</p>
  </div>
</template>


